/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ninja_hon95_jlaw_JlawLcd */

#ifndef _Included_ninja_hon95_jlaw_JlawLcd
#define _Included_ninja_hon95_jlaw_JlawLcd
#ifdef __cplusplus
extern "C" {
#endif
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_MONO
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_MONO 1L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_COLOR
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_COLOR 2L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_BOTH
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_TYPE_BOTH 3L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_0
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_0 1L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_1
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_1 2L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_2
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_2 4L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_3
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BUTTON_3 8L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_LEFT
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_LEFT 256L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_RIGHT
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_RIGHT 512L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_OK
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_OK 1024L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_CANCEL
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_CANCEL 2048L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_UP
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_UP 4096L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_DOWN
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_DOWN 8192L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_MENU
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BUTTON_MENU 16384L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_WIDTH
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_WIDTH 160L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_HEIGHT
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_HEIGHT 43L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_WIDTH
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_WIDTH 320L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_HEIGHT
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_HEIGHT 240L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BITMAP_SIZE
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_MONO_BITMAP_SIZE 6880L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BITMAP_BYTES_PER_PIXEL
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BITMAP_BYTES_PER_PIXEL 4L
#undef ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BITMAP_SIZE
#define ninja_hon95_jlaw_JlawLcd_LOGI_LCD_COLOR_BITMAP_SIZE 307200L
/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdInit
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdInit
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdIsConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdIsConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdIsButtonPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdIsButtonPressed
  (JNIEnv *, jclass, jint);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdUpdate
  (JNIEnv *, jclass);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdShutdown
  (JNIEnv *, jclass);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdMonoSetBackground
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdMonoSetBackground
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdMonoSetText
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdMonoSetText
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdColorSetBackground
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdColorSetBackground
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdColorSetTitle
 * Signature: (Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdColorSetTitle
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     ninja_hon95_jlaw_JlawLcd
 * Method:    nLogiLcdColorSetText
 * Signature: (ILjava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawLcd_nLogiLcdColorSetText
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
