/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ninja_hon95_jlaw_JlawArxControl */

#ifndef _Included_ninja_hon95_jlaw_JlawArxControl
#define _Included_ninja_hon95_jlaw_JlawArxControl
#ifdef __cplusplus
extern "C" {
#endif
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_FOCUS_ACTIVE
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_FOCUS_ACTIVE 1L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_FOCUS_INACTIVE
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_FOCUS_INACTIVE 2L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_TAP_ON_TAG
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_TAP_ON_TAG 4L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_MOBILEDEVICE_ARRIVAL
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_MOBILEDEVICE_ARRIVAL 8L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_MOBILEDEVICE_REMOVAL
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_EVENT_MOBILEDEVICE_REMOVAL 16L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_IPHONE
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_IPHONE 1L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_IPAD
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_IPAD 2L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_SMALL
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_SMALL 3L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_NORMAL
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_NORMAL 4L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_LARGE
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_LARGE 5L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_XLARGE
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_XLARGE 6L
#undef ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_OTHER
#define ninja_hon95_jlaw_JlawArxControl_LOGI_ARX_DEVICETYPE_ANDROID_OTHER 7L
/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lninja/hon95/jlaw/JlawArxControl/JlawArxControlCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxInit
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxAddFileAs
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxAddFileAs
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxAddContentAs
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxAddContentAs
  (JNIEnv *, jclass, jbyteArray, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxAddUTF8StringAs
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxAddUTF8StringAs
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxAddImageFromBitmap
 * Signature: ([BIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxAddImageFromBitmap
  (JNIEnv *, jclass, jbyteArray, jint, jint, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxSetIndex
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxSetIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxSetTagPropertyById
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxSetTagPropertyById
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxSetTagsPropertyByClass
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxSetTagsPropertyByClass
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxSetTagContentById
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxSetTagContentById
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxSetTagsContentByClass
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxSetTagsContentByClass
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxGetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxGetLastError
  (JNIEnv *, jclass);

/*
 * Class:     ninja_hon95_jlaw_JlawArxControl
 * Method:    nLogiArxShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ninja_hon95_jlaw_JlawArxControl_nLogiArxShutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ninja_hon95_jlaw_JlawArxControl_JlawArxControlCallback */

#ifndef _Included_ninja_hon95_jlaw_JlawArxControl_JlawArxControlCallback
#define _Included_ninja_hon95_jlaw_JlawArxControl_JlawArxControlCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
